//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratacion
    {
        [DisplayName("Codigo de persona")]
        public decimal codPersona { get; set; }
        [DisplayName("Codigo del equipo")]
        public decimal codEquipo { get; set; }
        [DisplayName("Importe")]
        public decimal importe { get; set; }
        [DisplayName("Fecha de contratacion")]
        public System.DateTime fechaContratacion { get; set; }
        [DisplayName("Fecha de baja")]
        public System.DateTime fechaBaja { get; set; }
        [DisplayName("Usuario creador")]
        public string usuarioCreador { get; set; }
        [DisplayName("Usuario modificador")]
        public string usuarioModificador { get; set; }
        [DisplayName("Fecha de creacion")]
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        [DisplayName("Fecha de modificacion")]
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual FuncionarioDeportivo FuncionarioDeportivo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
