//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadJugador
    {
        public decimal codEspecialidad { get; set; }
        public decimal gradoEspecialidad { get; set; }
        public decimal codPersona { get; set; }
        public string usuarioCreador { get; set; }
        public string usuarioModificador { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Jugador Jugador { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
