//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hist_CambioPartido
    {
        public decimal codPartido { get; set; }
        public decimal jugadorSale { get; set; }
        public decimal jugadorEntra { get; set; }
        public decimal minuto { get; set; }
    
        public virtual Hist_Partido Hist_Partido { get; set; }
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
