//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hist_Fecha
    {
        public decimal codFecha { get; set; }
        public decimal codTorneo { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Hist_Torneo Hist_Torneo { get; set; }
    }
}
