//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hist_Partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hist_Partido()
        {
            this.Hist_AlineacionPartido = new HashSet<Hist_AlineacionPartido>();
            this.Hist_AnotadorPartido = new HashSet<Hist_AnotadorPartido>();
            this.Hist_CambioPartido = new HashSet<Hist_CambioPartido>();
            this.Hist_PartidoArbitro = new HashSet<Hist_PartidoArbitro>();
        }
    
        public decimal codPartido { get; set; }
        public Nullable<decimal> codFecha { get; set; }
        public decimal codEquipo1 { get; set; }
        public decimal codEquipo2 { get; set; }
        public Nullable<decimal> golesEquipo1 { get; set; }
        public Nullable<decimal> golesEquipo2 { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_AlineacionPartido> Hist_AlineacionPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_AnotadorPartido> Hist_AnotadorPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_CambioPartido> Hist_CambioPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_PartidoArbitro> Hist_PartidoArbitro { get; set; }
    }
}
