//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.AlineacionPartido = new HashSet<AlineacionPartido>();
            this.AnotadorPartido = new HashSet<AnotadorPartido>();
            this.CambioPartido = new HashSet<CambioPartido>();
            this.CambioPartido1 = new HashSet<CambioPartido>();
            this.EspecialidadJugador = new HashSet<EspecialidadJugador>();
            this.Hist_AlineacionPartido = new HashSet<Hist_AlineacionPartido>();
            this.Hist_AnotadorPartido = new HashSet<Hist_AnotadorPartido>();
            this.Hist_CambioPartido = new HashSet<Hist_CambioPartido>();
            this.Hist_CambioPartido1 = new HashSet<Hist_CambioPartido>();
        }
        [DisplayName("Codigo de persona")]
        public decimal codPersona { get; set; }
        [DisplayName("Peso del jugador")]
        public decimal pesoJugador { get; set; }
        [DisplayName("Altura del jugador")]
        public decimal alturaJugador { get; set; }
        [DisplayName("Codigo del equipo")]
        public decimal codEquipo { get; set; }
        [DisplayName("Usuario creador")]
        public string usuarioCreador { get; set; }
        [DisplayName("Usuario modificador")]
        public string usuarioModificador { get; set; }
        [DisplayName("Fecha de creacion")]
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        [DisplayName("Fecha de modificacion")]
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlineacionPartido> AlineacionPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnotadorPartido> AnotadorPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioPartido> CambioPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioPartido> CambioPartido1 { get; set; }
        public virtual Equipo Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialidadJugador> EspecialidadJugador { get; set; }
        public virtual FuncionarioDeportivo FuncionarioDeportivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_AlineacionPartido> Hist_AlineacionPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_AnotadorPartido> Hist_AnotadorPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_CambioPartido> Hist_CambioPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_CambioPartido> Hist_CambioPartido1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
