//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partido()
        {
            this.AlineacionPartido = new HashSet<AlineacionPartido>();
            this.AnotadorPartido = new HashSet<AnotadorPartido>();
            this.CambioPartido = new HashSet<CambioPartido>();
            this.PartidoArbitro = new HashSet<PartidoArbitro>();
        }
        [DisplayName("Codigo del partido"), DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal codPartido { get; set; }
        [DisplayName("Codigo de fecha")]
        public Nullable<decimal> codFecha { get; set; }
        [DisplayName("Codigo del equipo 1"), DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal codEquipo1 { get; set; }
        [DisplayName("Codigo del equipo 2"), DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal codEquipo2 { get; set; }
        [DisplayName("Goles del equipo 2"), DisplayFormat(DataFormatString = "{0:N0}")]
        public Nullable<decimal> golesEquipo1 { get; set; }
        [DisplayName("Goles del equipo 2"), DisplayFormat(DataFormatString = "{0:N0}")]
        public Nullable<decimal> golesEquipo2 { get; set; }
        [DisplayName("Usuario creador")]
        public string usuarioCreador { get; set; }
        [DisplayName("Usuario modificador")]
        public string usuarioModificador { get; set; }
        [DisplayName("Fecha de creacion")]
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        [DisplayName("Fecha de modificacion")]
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlineacionPartido> AlineacionPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnotadorPartido> AnotadorPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioPartido> CambioPartido { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
        public virtual Fecha Fecha { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartidoArbitro> PartidoArbitro { get; set; }
    }
}
